[General]
hotkey=Alt+Space
showTray=false
telemetry=false
terminal=kitty

[org.albert.extension.applications]
enabled=true
fuzzy=true
use_generic_name=false
use_keywords=false

[org.albert.extension.calculator]
enabled=true

[org.albert.extension.externalextensions]
enabled=false

[org.albert.extension.python]
enabled=true
enabled_modules=@Invalid()

[org.albert.extension.ssh]
enabled=true

[org.albert.extension.system]
enabled=true
lock=betterlockscreen -l

[org.albert.extension.terminal]
enabled=false

[org.albert.frontend.widgetboxmodel]
alwaysOnTop=true
clearOnHide=true
displayIcons=true
displayScrollbar=false
displayShadow=false
hideOnClose=false
hideOnFocusLoss=true
itemCount=10
showCentered=true
theme=Yosemite
windowPosition=@Point(637 293)
